from agent_manager.agents.starcraft2_agent.gpt_agent import GPTAgent
from agent_manager.agents.civ_agent.mastaba_agent import MastabaAgent
from agent_manager.agents.stratego_agent.stratego_agent import StrategoAgent
from agent_manager.agents.streetfight3_agent.streetfight3_agent import StreetFight3Agent
from agent_manager.agents.welfare_diplomacy.wd_agent import WDAgent
from agent_manager.agents.were_wolf.were_wolf_agent import WereWolfAgent
